"""init

Revision ID: 4538f4acc9b0
Revises: 
Create Date: 2026-05-13 18:58:12.876899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4538f4acc9b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('bg_color_start', sa.String(), nullable=True),
    sa.Column('bg_color_end', sa.String(), nullable=True),
    sa.Column('redirect_type', sa.String(), nullable=True),
    sa.Column('redirect_target', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('scheme_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relative_name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('since_date', sa.Date(), nullable=False),
    sa.Column('gram_seva_user_id', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('added_by_admin_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('emergency', 'official', 'health', 'education', 'service_provider', name='contactcategory'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('office_hours', sa.String(), nullable=True),
    sa.Column('requires_permission', sa.Boolean(), nullable=False),
    sa.Column('how_to_talk', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('guides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_hindi', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ration_card', 'birth_certificate', 'caste_certificate', 'income_certificate', 'aadhaar', 'pension', 'land_records', 'health', 'education', 'other', name='guidecategory'), nullable=False),
    sa.Column('office_name', sa.String(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('timings', sa.String(), nullable=True),
    sa.Column('approximate_cost', sa.String(), nullable=True),
    sa.Column('estimated_time', sa.String(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('documents_needed', sa.Text(), nullable=True),
    sa.Column('online_link', sa.String(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('government', 'private', 'railway', 'banking', 'defence', 'teaching', 'other', name='jobcategory'), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=False),
    sa.Column('how_to_apply', sa.Text(), nullable=False),
    sa.Column('apply_link', sa.String(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('purpose', sa.Enum('registration', 'login', 'reset_password', 'account_deletion', name='otppurpose'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_phone'), 'otps', ['phone'], unique=False)
    op.create_table('rating_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=False),
    sa.Column('how_to_apply', sa.Text(), nullable=False),
    sa.Column('official_link', sa.String(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('health', 'farming', 'education', 'housing', 'finance', 'women', 'other', name='schemecategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'vendor', 'user', name='userrole'), nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('verification_photo_url', sa.String(), nullable=True),
    sa.Column('is_durbe_resident', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('badge', sa.String(), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vendor_listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('village_id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_name_hindi', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('crops', 'animal_feed', name='vendorcategory'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('stock_status', sa.Enum('in_stock', 'limited', 'out_of_stock', name='stockstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gram_awaaz',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('department', sa.Enum('panchayat', 'bdo', 'pwd', 'health', 'police', 'education', 'electricity', 'water', 'other', name='department'), nullable=False),
    sa.Column('demand', sa.Text(), nullable=False),
    sa.Column('photo_url_1', sa.String(), nullable=False),
    sa.Column('photo_url_2', sa.String(), nullable=True),
    sa.Column('photo_url_3', sa.String(), nullable=True),
    sa.Column('photo_url_4', sa.String(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gram_sabha',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('decisions', sa.Text(), nullable=False),
    sa.Column('attendees_count', sa.Integer(), nullable=False),
    sa.Column('minutes_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applicants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relative_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('gram_seva_user_id', sa.String(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['gram_seva_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neta_ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('neta_id', sa.String(), nullable=False),
    sa.Column('window_id', sa.String(), nullable=False),
    sa.Column('rated_by', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['neta_id'], ['netas.id'], ),
    sa.ForeignKeyConstraint(['rated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['rating_windows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neta_id', 'window_id', 'rated_by', name='uq_one_rating_per_window')
    )
    op.create_table('vikas_prastav',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('road', 'water', 'education', 'health', 'electricity', 'agriculture', 'other', name='proposalcategory'), nullable=False),
    sa.Column('estimated_cost', sa.String(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('photo_url_1', sa.String(), nullable=False),
    sa.Column('photo_url_2', sa.String(), nullable=True),
    sa.Column('photo_url_3', sa.String(), nullable=True),
    sa.Column('photo_url_4', sa.String(), nullable=True),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gram_awaaz_upvotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['gram_awaaz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vikas_prastav_upvotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['vikas_prastav.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vikas_prastav_upvotes')
    op.drop_table('gram_awaaz_upvotes')
    op.drop_table('vikas_prastav')
    op.drop_table('neta_ratings')
    op.drop_table('job_applicants')
    op.drop_table('gram_sabha')
    op.drop_table('gram_awaaz')
    op.drop_table('vendor_listings')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('schemes')
    op.drop_table('rating_windows')
    op.drop_index(op.f('ix_otps_phone'), table_name='otps')
    op.drop_table('otps')
    op.drop_table('netas')
    op.drop_table('job_alerts')
    op.drop_table('guides')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('community_members')
    op.drop_table('banners')
    # ### end Alembic commands ###
