"""add_job_alerts_table

Revision ID: 9000868de1bd
Revises: 1692994afff0
Create Date: 2026-04-22 02:31:55.411436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9000868de1bd'
down_revision: Union[str, Sequence[str], None] = '1692994afff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_alerts')
    op.drop_table('vendor_listings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_listings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('village_id', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(), nullable=False),
    sa.Column('product_name_hindi', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=11), nullable=False),
    sa.Column('price', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('stock_status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_alerts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('village_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('organization', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=12), nullable=False),
    sa.Column('total_posts', sa.INTEGER(), nullable=True),
    sa.Column('eligibility', sa.TEXT(), nullable=False),
    sa.Column('how_to_apply', sa.TEXT(), nullable=False),
    sa.Column('apply_link', sa.VARCHAR(), nullable=True),
    sa.Column('last_date', sa.DATE(), nullable=False),
    sa.Column('salary_range', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
