"""add_neta_ratingwindow_netarating_tables

Revision ID: e3258a404f92
Revises: ebc48b1fee31
Create Date: 2026-04-29 01:25:13.014788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3258a404f92'
down_revision: Union[str, Sequence[str], None] = 'ebc48b1fee31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
