"""photo_url_1_to_4_gram_awaaz_vikas_prastav

Revision ID: ebc48b1fee31
Revises: 994d34cac388
Create Date: 2026-04-25 11:04:01.011491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc48b1fee31'
down_revision: Union[str, Sequence[str], None] = '994d34cac388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_listings')
    op.drop_table('job_alerts')
    op.drop_table('community_members')
    op.add_column('gram_awaaz', sa.Column('photo_url_1', sa.String(), nullable=False))
    op.add_column('gram_awaaz', sa.Column('photo_url_2', sa.String(), nullable=True))
    op.add_column('gram_awaaz', sa.Column('photo_url_3', sa.String(), nullable=True))
    op.add_column('gram_awaaz', sa.Column('photo_url_4', sa.String(), nullable=True))
    op.drop_column('gram_awaaz', 'photo_url')
    op.add_column('vikas_prastav', sa.Column('photo_url_1', sa.String(), nullable=False))
    op.add_column('vikas_prastav', sa.Column('photo_url_2', sa.String(), nullable=True))
    op.add_column('vikas_prastav', sa.Column('photo_url_3', sa.String(), nullable=True))
    op.add_column('vikas_prastav', sa.Column('photo_url_4', sa.String(), nullable=True))
    op.drop_column('vikas_prastav', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vikas_prastav', sa.Column('photo_url', sa.VARCHAR(), nullable=False))
    op.drop_column('vikas_prastav', 'photo_url_4')
    op.drop_column('vikas_prastav', 'photo_url_3')
    op.drop_column('vikas_prastav', 'photo_url_2')
    op.drop_column('vikas_prastav', 'photo_url_1')
    op.add_column('gram_awaaz', sa.Column('photo_url', sa.VARCHAR(), nullable=False))
    op.drop_column('gram_awaaz', 'photo_url_4')
    op.drop_column('gram_awaaz', 'photo_url_3')
    op.drop_column('gram_awaaz', 'photo_url_2')
    op.drop_column('gram_awaaz', 'photo_url_1')
    op.create_table('community_members',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('village_id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=True),
    sa.Column('scheme_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('relative_name', sa.VARCHAR(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=False),
    sa.Column('since_date', sa.DATE(), nullable=False),
    sa.Column('gram_seva_user_id', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), nullable=True),
    sa.Column('added_by_admin_id', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_alerts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('village_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('organization', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=12), nullable=False),
    sa.Column('total_posts', sa.INTEGER(), nullable=True),
    sa.Column('eligibility', sa.TEXT(), nullable=False),
    sa.Column('how_to_apply', sa.TEXT(), nullable=False),
    sa.Column('apply_link', sa.VARCHAR(), nullable=True),
    sa.Column('last_date', sa.DATE(), nullable=False),
    sa.Column('salary_range', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_listings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('village_id', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_id', sa.VARCHAR(), nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(), nullable=False),
    sa.Column('product_name', sa.VARCHAR(), nullable=False),
    sa.Column('product_name_hindi', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=11), nullable=False),
    sa.Column('price', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('stock_status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
